# Generated by Django 2.2.10 on 2021-04-04 19:29

import Account.models
from django.db import migrations, models
import django.db.models.manager
import override_existing


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='abc', max_length=30, unique=True, verbose_name='Username')),
                ('fullname', models.CharField(default='ABC XYZ', max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(default='abc@def.gh', max_length=100, verbose_name='Email Address')),
                ('phone', models.CharField(default='012-3456-7890', max_length=15, verbose_name='Phone Number')),
                ('photo', models.ImageField(blank=True, storage=override_existing.OverrideExisting(), upload_to=Account.models.photo_path, verbose_name='Photo ID')),
                ('barcode', models.ImageField(blank=True, storage=override_existing.OverrideExisting(), upload_to=Account.models.barcode_path, verbose_name='Barcode ID')),
                ('password', models.CharField(default='pwd', max_length=80, verbose_name='Password')),
                ('realPassword', models.CharField(default='pwd', max_length=30, verbose_name='Raw Password')),
                ('dateSignUp', models.DateTimeField(auto_now=True, verbose_name='Date Signed Up')),
                ('lastLogin', models.DateTimeField(auto_now_add=True, verbose_name='Last Time Login')),
                ('isAdmin', models.BooleanField(default=False, verbose_name='Administrator access')),
                ('isStaff', models.BooleanField(default=False, verbose_name='Staff access')),
                ('isActive', models.BooleanField(default=True, verbose_name='Activated')),
            ],
            options={
                'db_table': 'account_table',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
