# Generated by Django 2.2.10 on 2021-04-04 19:29

import Shipment.models
from django.db import migrations, models
import override_existing


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('number', models.BigAutoField(db_column='no', primary_key=True, serialize=False)),
                ('barcode', models.ImageField(blank=True, db_column='barcode', storage=override_existing.OverrideExisting(), upload_to=Shipment.models.barcode_path, verbose_name='Barcode Shipment')),
                ('kantor_id', models.CharField(blank=True, db_column='kantor_id', max_length=40)),
                ('insert_org', models.CharField(blank=True, db_column='insert_org', max_length=100)),
                ('correct_org', models.CharField(blank=True, db_column='correct_org', max_length=100)),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='regdate', max_length=6)),
                ('company', models.CharField(choices=[('GLOVIS', 'GLOVIS'), ('INTERGIS', 'INTERGIS'), ('KSS', 'KSS'), ('SHI OCEAN', 'SHI OCEAN'), ('SUNRIO', 'SUNRIO'), ('보성상사', '보성상사'), ('KLCSM', 'KLCSM'), ('POSSM', 'POSSM'), ('FORTUNE WILL', 'FORTUNE WILL'), ('MAN', 'MAN'), ('STX', 'STX'), ('CENTRA', 'CENTRA'), ('GOLTENS', 'GOLTENS'), ('DAN MO', 'DAN MO'), ('SUNAMI', 'SUNAMI'), ('DORVAL', 'DORVAL'), ('MARUBISHI', 'MARUBISHI'), ('KNK', 'KNK'), ('SAEHAN', 'SAEHAN'), ('GOWIN', 'GOWIN'), ('이강공사', '이강공사'), ('EUCO', 'EUCO'), ('SEOYANG', 'SEOYANG'), ('오션마린', '오션마린'), ('CMSHIP', 'CMSHIP')], db_column='company', max_length=100, verbose_name='COMPANY')),
                ('vessel', models.CharField(blank=True, db_column='vessel', max_length=100, verbose_name='VESSEL')),
                ('by', models.CharField(blank=True, choices=[('FDX', 'FDX'), ('DHL', 'DHL'), ('SEA', 'SEA'), ('TNT', 'TNT'), ('AIR', 'AIR'), ('SFX', 'SFX')], db_column='by1', max_length=50, verbose_name='BY')),
                ('BLno', models.CharField(blank=True, db_column='blno', max_length=50, verbose_name='BLNO')),
                ('docs', models.TextField(blank=True, db_column='doc', max_length=500, verbose_name='DOC')),
                ('odr', models.TextField(blank=True, db_column='odr', max_length=100, verbose_name='ODR')),
                ('supplier', models.TextField(blank=True, db_column='supplier', max_length=100, verbose_name='SUPPLIER')),
                ('quanty', models.CharField(blank=True, db_column='qty', max_length=10, verbose_name='QTY')),
                ('unit', models.CharField(blank=True, db_column='unit', max_length=10, verbose_name='UNIT')),
                ('size', models.TextField(blank=True, db_column='size', max_length=100, verbose_name='SIZE')),
                ('weight', models.CharField(blank=True, db_column='weight', max_length=10, verbose_name='WEIGHT')),
                ('in_date', models.DateTimeField(blank=True, db_column='in1', max_length=6, null=True, verbose_name='IN')),
                ('warehouse', models.CharField(blank=True, choices=[('ICN-IGS', 'ICN-IGS'), ('SL', 'SL'), ('KIM-IGS', 'KIM-IGS')], db_column='whouse', max_length=100, verbose_name='W/H')),
                ('port', models.CharField(blank=True, db_column='port', max_length=100, verbose_name='PORT')),
                ('out_date', models.DateTimeField(blank=True, db_column='out1', max_length=6, null=True, verbose_name='OUT')),
                ('remark', models.TextField(blank=True, db_column='remark', max_length=500, verbose_name='REMARK')),
                ('image', models.ImageField(blank=True, db_column='img', storage=override_existing.OverrideExisting(), upload_to=Shipment.models.image_path, verbose_name='IMG')),
                ('image1', models.ImageField(blank=True, db_column='img1', storage=override_existing.OverrideExisting(), upload_to=Shipment.models.image_path)),
                ('image2', models.ImageField(blank=True, db_column='img2', storage=override_existing.OverrideExisting(), upload_to=Shipment.models.image_path)),
                ('pdf_file', models.FileField(blank=True, db_column='pdf', storage=override_existing.OverrideExisting(), upload_to=Shipment.models.pdf_path, verbose_name='PDF')),
                ('division', models.CharField(blank=True, choices=[('D', 'D'), ('L', 'L'), ('B', 'B')], db_column='division', max_length=10, verbose_name='DIVISION')),
                ('flag_status', models.CharField(blank=True, choices=[('COMPLETED', 'COMPLETED'), ('START', 'START'), ('STAY', 'STAY'), ('BLANK', 'BLANK')], db_column='flg', max_length=10, verbose_name='STATE')),
                ('job_number', models.CharField(blank=True, db_column='jobno', max_length=50, verbose_name='JOB.NO')),
                ('work', models.CharField(blank=True, db_column='work', max_length=10)),
                ('work_regdate', models.DateTimeField(blank=True, db_column='work_regdate', max_length=6, null=True)),
            ],
            options={
                'db_table': 'pla_databoard',
            },
        ),
    ]
