# Generated by Django 2.2.10 on 2021-04-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='by',
            field=models.CharField(blank=True, choices=[('FDX', 'FDX'), ('TNT', 'TNT'), ('SFX', 'SFX'), ('DHL', 'DHL'), ('AIR', 'AIR'), ('SEA', 'SEA')], db_column='by1', max_length=50, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(choices=[('보성상사', '보성상사'), ('KSS', 'KSS'), ('EUCO', 'EUCO'), ('FORTUNE WILL', 'FORTUNE WILL'), ('MAN', 'MAN'), ('SAEHAN', 'SAEHAN'), ('STX', 'STX'), ('GOWIN', 'GOWIN'), ('KLCSM', 'KLCSM'), ('CMSHIP', 'CMSHIP'), ('CENTRA', 'CENTRA'), ('INTERGIS', 'INTERGIS'), ('이강공사', '이강공사'), ('DAN MO', 'DAN MO'), ('GOLTENS', 'GOLTENS'), ('오션마린', '오션마린'), ('GLOVIS', 'GLOVIS'), ('SEOYANG', 'SEOYANG'), ('SHI OCEAN', 'SHI OCEAN'), ('POSSM', 'POSSM'), ('KNK', 'KNK'), ('SUNAMI', 'SUNAMI'), ('SUNRIO', 'SUNRIO'), ('MARUBISHI', 'MARUBISHI'), ('DORVAL', 'DORVAL')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('L', 'L'), ('D', 'D')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('START', 'START'), ('STAY', 'STAY'), ('COMPLETED', 'COMPLETED'), ('BLANK', 'BLANK')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='warehouse',
            field=models.CharField(blank=True, choices=[('KIM-IGS', 'KIM-IGS'), ('SL', 'SL'), ('ICN-IGS', 'ICN-IGS')], db_column='whouse', max_length=100, verbose_name='W/H'),
        ),
    ]
