# Generated by Django 2.2.10 on 2021-04-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0002_auto_20210404_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='by',
            field=models.CharField(blank=True, choices=[('SFX', 'SFX'), ('TNT', 'TNT'), ('SEA', 'SEA'), ('DHL', 'DHL'), ('FDX', 'FDX'), ('AIR', 'AIR')], db_column='by1', max_length=50, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(choices=[('KLCSM', 'KLCSM'), ('KNK', 'KNK'), ('DAN MO', 'DAN MO'), ('MAN', 'MAN'), ('보성상사', '보성상사'), ('MARUBISHI', 'MARUBISHI'), ('SHI OCEAN', 'SHI OCEAN'), ('CMSHIP', 'CMSHIP'), ('POSSM', 'POSSM'), ('SEOYANG', 'SEOYANG'), ('SUNAMI', 'SUNAMI'), ('STX', 'STX'), ('SAEHAN', 'SAEHAN'), ('KSS', 'KSS'), ('FORTUNE WILL', 'FORTUNE WILL'), ('INTERGIS', 'INTERGIS'), ('SUNRIO', 'SUNRIO'), ('GOWIN', 'GOWIN'), ('이강공사', '이강공사'), ('오션마린', '오션마린'), ('DORVAL', 'DORVAL'), ('CENTRA', 'CENTRA'), ('EUCO', 'EUCO'), ('GOLTENS', 'GOLTENS'), ('GLOVIS', 'GLOVIS')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('L', 'L'), ('D', 'D'), ('B', 'B')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('START', 'START'), ('COMPLETED', 'COMPLETED'), ('BLANK', 'BLANK'), ('STAY', 'STAY')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='warehouse',
            field=models.CharField(blank=True, choices=[('ICN-IGS', 'ICN-IGS'), ('SL', 'SL'), ('KIM-IGS', 'KIM-IGS')], db_column='whouse', max_length=100, verbose_name='W/H'),
        ),
    ]
