# Generated by Django 2.2.10 on 2021-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0003_auto_20210404_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='by',
            field=models.CharField(blank=True, choices=[('SEA', 'SEA'), ('AIR', 'AIR'), ('DHL', 'DHL'), ('SFX', 'SFX'), ('FDX', 'FDX'), ('TNT', 'TNT')], db_column='by1', max_length=50, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(choices=[('DORVAL', 'DORVAL'), ('GOWIN', 'GOWIN'), ('CENTRA', 'CENTRA'), ('KSS', 'KSS'), ('SEOYANG', 'SEOYANG'), ('SUNRIO', 'SUNRIO'), ('INTERGIS', 'INTERGIS'), ('STX', 'STX'), ('이강공사', '이강공사'), ('SAEHAN', 'SAEHAN'), ('보성상사', '보성상사'), ('CMSHIP', 'CMSHIP'), ('KLCSM', 'KLCSM'), ('POSSM', 'POSSM'), ('SUNAMI', 'SUNAMI'), ('DAN MO', 'DAN MO'), ('MAN', 'MAN'), ('FORTUNE WILL', 'FORTUNE WILL'), ('EUCO', 'EUCO'), ('오션마린', '오션마린'), ('MARUBISHI', 'MARUBISHI'), ('KNK', 'KNK'), ('SHI OCEAN', 'SHI OCEAN'), ('GLOVIS', 'GLOVIS'), ('GOLTENS', 'GOLTENS')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('B', 'B'), ('L', 'L')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'COMPLETED'), ('BLANK', 'BLANK'), ('START', 'START'), ('STAY', 'STAY')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='in_date',
            field=models.DateTimeField(blank=True, db_column='in1', max_length=8, null=True, verbose_name='IN'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='odr',
            field=models.TextField(db_column='odr', max_length=100, verbose_name='ODR'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='out_date',
            field=models.DateTimeField(blank=True, db_column='out1', max_length=8, null=True, verbose_name='OUT'),
        ),
    ]
