# Generated by Django 2.2.10 on 2021-04-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0004_auto_20210410_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='by',
            field=models.CharField(blank=True, choices=[('DHL', 'DHL'), ('SFX', 'SFX'), ('SEA', 'SEA'), ('AIR', 'AIR'), ('TNT', 'TNT'), ('FDX', 'FDX')], db_column='by1', max_length=50, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(choices=[('CENTRA', 'CENTRA'), ('GOLTENS', 'GOLTENS'), ('KNK', 'KNK'), ('SAEHAN', 'SAEHAN'), ('GLOVIS', 'GLOVIS'), ('보성상사', '보성상사'), ('INTERGIS', 'INTERGIS'), ('FORTUNE WILL', 'FORTUNE WILL'), ('SEOYANG', 'SEOYANG'), ('MAN', 'MAN'), ('SUNRIO', 'SUNRIO'), ('DAN MO', 'DAN MO'), ('KLCSM', 'KLCSM'), ('KSS', 'KSS'), ('오션마린', '오션마린'), ('EUCO', 'EUCO'), ('POSSM', 'POSSM'), ('STX', 'STX'), ('이강공사', '이강공사'), ('DORVAL', 'DORVAL'), ('SHI OCEAN', 'SHI OCEAN'), ('CMSHIP', 'CMSHIP'), ('MARUBISHI', 'MARUBISHI'), ('SUNAMI', 'SUNAMI'), ('GOWIN', 'GOWIN')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('L', 'L'), ('D', 'D'), ('B', 'B')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'COMPLETED'), ('BLANK', 'BLANK'), ('STAY', 'STAY'), ('START', 'START')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='in_date',
            field=models.DateTimeField(blank=True, db_column='in1', max_length=10, null=True, verbose_name='IN'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='out_date',
            field=models.DateTimeField(blank=True, db_column='out1', max_length=10, null=True, verbose_name='OUT'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='warehouse',
            field=models.CharField(blank=True, choices=[('KIM-IGS', 'KIM-IGS'), ('ICN-IGS', 'ICN-IGS'), ('SL', 'SL')], db_column='whouse', max_length=100, verbose_name='W/H'),
        ),
    ]
