# Generated by Django 2.2.10 on 2021-04-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0006_auto_20210410_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='by',
            field=models.CharField(blank=True, choices=[('SEA', 'SEA'), ('TNT', 'TNT'), ('DHL', 'DHL'), ('FDX', 'FDX'), ('AIR', 'AIR'), ('SFX', 'SFX')], db_column='by1', max_length=50, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(choices=[('FORTUNE WILL', 'FORTUNE WILL'), ('KSS', 'KSS'), ('SEOYANG', 'SEOYANG'), ('SHI OCEAN', 'SHI OCEAN'), ('보성상사', '보성상사'), ('STX', 'STX'), ('SUNAMI', 'SUNAMI'), ('GLOVIS', 'GLOVIS'), ('SUNRIO', 'SUNRIO'), ('INTERGIS', 'INTERGIS'), ('SAEHAN', 'SAEHAN'), ('DORVAL', 'DORVAL'), ('이강공사', '이강공사'), ('DAN MO', 'DAN MO'), ('POSSM', 'POSSM'), ('GOLTENS', 'GOLTENS'), ('EUCO', 'EUCO'), ('CMSHIP', 'CMSHIP'), ('CENTRA', 'CENTRA'), ('GOWIN', 'GOWIN'), ('KNK', 'KNK'), ('MARUBISHI', 'MARUBISHI'), ('오션마린', '오션마린'), ('KLCSM', 'KLCSM'), ('MAN', 'MAN')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'COMPLETED'), ('START', 'START'), ('BLANK', 'BLANK'), ('STAY', 'STAY')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
    ]
