# Generated by Django 2.2.10 on 2021-04-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0007_auto_20210410_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='by',
            field=models.CharField(blank=True, choices=[('TNT', 'TNT'), ('AIR', 'AIR'), ('FDX', 'FDX'), ('SFX', 'SFX'), ('SEA', 'SEA'), ('DHL', 'DHL')], db_column='by1', max_length=50, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(choices=[('POSSM', 'POSSM'), ('CENTRA', 'CENTRA'), ('GOLTENS', 'GOLTENS'), ('SEOYANG', 'SEOYANG'), ('이강공사', '이강공사'), ('오션마린', '오션마린'), ('DAN MO', 'DAN MO'), ('SHI OCEAN', 'SHI OCEAN'), ('SUNAMI', 'SUNAMI'), ('SUNRIO', 'SUNRIO'), ('KSS', 'KSS'), ('GLOVIS', 'GLOVIS'), ('STX', 'STX'), ('KLCSM', 'KLCSM'), ('MAN', 'MAN'), ('KNK', 'KNK'), ('FORTUNE WILL', 'FORTUNE WILL'), ('SAEHAN', 'SAEHAN'), ('CMSHIP', 'CMSHIP'), ('DORVAL', 'DORVAL'), ('EUCO', 'EUCO'), ('INTERGIS', 'INTERGIS'), ('GOWIN', 'GOWIN'), ('MARUBISHI', 'MARUBISHI'), ('보성상사', '보성상사')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('L', 'L'), ('D', 'D')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('BLANK', 'BLANK'), ('STAY', 'STAY'), ('COMPLETED', 'COMPLETED'), ('START', 'START')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='in_date',
            field=models.DateField(blank=True, db_column='in1', max_length=10, null=True, verbose_name='IN'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='out_date',
            field=models.DateField(blank=True, db_column='out1', max_length=10, null=True, verbose_name='OUT'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='warehouse',
            field=models.CharField(blank=True, choices=[('KIM-IGS', 'KIM-IGS'), ('ICN-IGS', 'ICN-IGS'), ('SL', 'SL')], db_column='whouse', max_length=100, verbose_name='W/H'),
        ),
    ]
