# Generated by Django 2.2.10 on 2021-04-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0008_auto_20210410_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='by',
            field=models.CharField(blank=True, choices=[('TNT', 'TNT'), ('FDX', 'FDX'), ('SEA', 'SEA'), ('SFX', 'SFX'), ('DHL', 'DHL'), ('AIR', 'AIR')], db_column='by1', max_length=50, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(choices=[('EUCO', 'EUCO'), ('CENTRA', 'CENTRA'), ('GLOVIS', 'GLOVIS'), ('GOLTENS', 'GOLTENS'), ('MAN', 'MAN'), ('SHI OCEAN', 'SHI OCEAN'), ('SUNRIO', 'SUNRIO'), ('SUNAMI', 'SUNAMI'), ('DAN MO', 'DAN MO'), ('STX', 'STX'), ('이강공사', '이강공사'), ('FORTUNE WILL', 'FORTUNE WILL'), ('KLCSM', 'KLCSM'), ('MARUBISHI', 'MARUBISHI'), ('CMSHIP', 'CMSHIP'), ('오션마린', '오션마린'), ('GOWIN', 'GOWIN'), ('POSSM', 'POSSM'), ('SEOYANG', 'SEOYANG'), ('보성상사', '보성상사'), ('DORVAL', 'DORVAL'), ('INTERGIS', 'INTERGIS'), ('KSS', 'KSS'), ('KNK', 'KNK'), ('SAEHAN', 'SAEHAN')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('L', 'L'), ('B', 'B'), ('D', 'D')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'COMPLETED'), ('STAY', 'STAY'), ('START', 'START'), ('BLANK', 'BLANK')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
    ]
